import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Header from "../components/Header"
import styled from "styled-components"
import ProjectCard from "../components/ProjectCard"
import Footer from "../components/Footer"

const Content = styled.div`
  padding: 24px 60px;
`

const ProjectDetail = styled.div`
  display: flex;
  align-items: flex-start;
  justify-content: space-between;

  .left {
    width: 50%;
    .title {
      display: flex;
      align-items: flex-start;
      border-bottom: 1px solid #bcffd7;
      padding-bottom: 12px;

      .project-detail {
        margin-left: 36px;
        h1 {
          margin: 0;
        }
      }
    }

    .description {
      margin-top: 24px;
    }
  }

  .right {
    background: linear-gradient(
      180deg,
      rgba(217, 217, 217, 0.25) 0%,
      rgba(217, 217, 217, 0) 0.01%
    );
    backdrop-filter: blur(50px);
    border-radius: 12px;

    padding: 28px;
    border: 1px solid #2ec747;
    width: 500px;

    .row {
      color: #8991dc;
      font-weight: 600;
      display: flex;
      justify-content: space-between;
      margin: 12px;
    }

    .amount {
      text-shadow: 0px 0px 20px rgba(255, 255, 255, 0.5);
      font-size: 32px;
      margin: 16px;
    }
  }
`

const TitleContainer = styled.div`
  display: flex;
  align-items: center;
  .dot {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background: linear-gradient(
      158.55deg,
      #2ec747 3.02%,
      rgba(0, 0, 0, 0.85) 46.62%,
      #8991dc 80.72%
    );
    margin-right: 24px;
  }

  .header {
    font-weight: bold;
    font-size: 24px;
  }
`

const ProjectSetting = styled.div`
  margin-top: 60px;
  display: flex;
  align-items: flex-start;
  justify-content: space-between;

  .left {
    width: 50%;
  }

  .right {
    background: linear-gradient(
      180deg,
      rgba(217, 217, 217, 0.25) 0%,
      rgba(217, 217, 217, 0) 0.01%
    );
    backdrop-filter: blur(50px);
    border-radius: 12px;

    padding: 28px;
    border: 1px solid #2ec747;
    width: 500px;

    .row {
      color: #8991dc;
      font-weight: 600;
      display: flex;
      justify-content: space-between;
      margin: 12px;
    }

    .amount {
      text-shadow: 0px 0px 20px rgba(255, 255, 255, 0.5);
      font-size: 32px;
      margin: 16px;
      display: flex;
      align-items: center;

      .dot-green {
        width: 20px;
        height: 20px;
        border-radius: 50%;
        background: #22da40e4;
        margin-right: 24px;
      }
    }
  }
`

const CreatorDetail = styled.div`
  display: flex;
  flex-direction: column;
  margin-top: 40px;
  flex-wrap: wrap;

  .title-container {
    display: flex;
    align-items: center;
  }

  .content {
    padding: 0 200px;
    display: flex;
    flex-direction: column;
    justify-content: center;

    .detail {
      margin-bottom: 12px;
      display: flex;
      flex-direction: column;
      span {
        margin-bottom: 4px;
      }
    }
  }
`

const CreateButton = styled.div`
  background: linear-gradient(
    90deg,
    #28a2b6 35.77%,
    rgba(76, 184, 121, 0.950611) 80.16%
  );
  box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.12);
  border-radius: 12px;
  width: 100%;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 28px;
  cursor: pointer;

  &:hover {
    opacity: 0.83;
  }
`

const OutlineButton = styled.div`
  background: transparent;
  border-radius: 12px;
  width: 100%;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 12px;
  cursor: pointer;
  color: #bcffd7;
  border: 1px solid #bcffd7;

  &:hover {
    opacity: 0.83;
  }
`

const Create: NextPage = () => {
  return (
    <div style={{ minHeight: "100vh" }}>
      <Head>
        <title>Staodio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content>
        <ProjectDetail>
          <div className="left">
            <div className="title">
              <Image src="/dog-small.svg" width={80} height={80} />
              <div className="project-detail">
                <h1>Project Name</h1>
                <p>0xdfdf...3ka0s3</p>
              </div>
            </div>
            <div className="description">
              <TitleContainer>
                <div className="dot" />
                <div className="header">Project Description</div>
              </TitleContainer>
              <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry's standard dummy
                text ever since the 1500s, when an unknown printer took a galley
                of type and scrambled it to make a type specimen book. It has
                survived not only five
              </p>
            </div>
          </div>
          <div className="right">
            <div className="row">Funding Goals</div>
            <div className="amount">1000 ETH</div>
            <div className="row">
              <span>Amount:</span>
              <span>10 ETH</span>
            </div>
            <div className="row">
              <span>Remain:</span>
              <span>5</span>
            </div>
            <div className="row">
              <span>Max Contributor:</span>
              <span>10</span>
            </div>
            <CreateButton>Contribute</CreateButton>
          </div>
        </ProjectDetail>

        <ProjectSetting>
          <div className="left">
            <TitleContainer>
              <div className="dot" />
              <div className="header">Project Setting</div>
            </TitleContainer>
          </div>
          <div className="right">
            <div className="amount">
              <div className="dot-green" />
              Edition Size
            </div>
            <div className="row">
              <span>Propose By:</span>
              <span>0xd3asd...334</span>
            </div>
            <div className="row">
              <span>Edition Size:</span>
              <span>5,000</span>
            </div>
            <div className="row">
              <span>Vote For:</span>
              <span>10</span>
            </div>
            <div className="row">
              <span>Vote Agianst:</span>
              <span>10</span>
            </div>
            <div className="row">
              <span>Total Vote:</span>
              <span>30</span>
            </div>
            <CreateButton>Vote For</CreateButton>
            <OutlineButton>Vote Agianst</OutlineButton>
          </div>
        </ProjectSetting>

        <CreatorDetail>
          <TitleContainer>
            <div className="dot" />
            <div className="header">Creator Detail</div>
          </TitleContainer>
          <div className="content">
            <Image src="/dog-small.svg" width={640} height={460} />
            <div className="detail">
              <span>Portfolio:</span>
              <b>gangKantapat.me</b>
            </div>
            <div className="detail">
              <span>Portfolio:</span>
              <b>gangKantapat.me</b>
            </div>
            <div className="detail">
              <span>Portfolio:</span>
              <b>gangKantapat.me</b>
            </div>
          </div>
        </CreatorDetail>
      </Content>
      <Footer />
    </div>
  )
}

export default Create
