import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Header from "../components/Header"
import styled from "styled-components"
import ProjectCard from "../components/ProjectCard"
import Footer from "../components/Footer"

const Content = styled.div`
  padding: 24px 60px;
`

const ProjectContainer = styled.div`
  display: flex;
  flex-direction: column;
  margin-top: 40px;
  flex-wrap: wrap;

  .title-container {
    display: flex;
    align-items: center;
  }

  .content {
    padding: 0 200px;
    display: flex;
    flex-direction: column;
    justify-content: center;
  }

  .dot {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background: linear-gradient(
      158.55deg,
      #2ec747 3.02%,
      rgba(0, 0, 0, 0.85) 46.62%,
      #8991dc 80.72%
    );
    margin-right: 24px;
  }

  .title {
    font-weight: bold;
    font-size: 24px;
  }
`

const InputRow = styled.div`
  width: 100%;
  margin-top: 32px;
`

const Label = styled.div`
  font-size: 18px;
`

const InputText = styled.input`
  background: rgba(168, 174, 186, 0.2);
  border-radius: 8px;
  width: 100%;
  height: 40px;
  color: #fff;
  padding: 12px;
  margin-top: 8px;
  outline: none;
  border: none;

  &:focus {
    border: 1px solid #abffb5;
  }
`

const CreateButton = styled.div`
  background: linear-gradient(
    90deg,
    #28a2b6 35.77%,
    rgba(76, 184, 121, 0.950611) 80.16%
  );
  box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.12);
  border-radius: 12px;
  width: 100%;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 28px;
  cursor: pointer;

  &:hover {
    opacity: 0.83;
  }
`

const Create: NextPage = () => {
  return (
    <div style={{ minHeight: "100vh" }}>
      <Head>
        <title>Staodio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content>
        <div style={{ display: "flex", justifyContent: "center" }}>
          <Image src="/asset.svg" width={400} height={290} />
        </div>
        <ProjectContainer>
          <div className="title-container">
            <div className="dot" />
            <div className="title">Project Detail</div>
          </div>
          <div className="content">
            <InputRow>
              <Label>Name</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>Symbol</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>Description</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>
                Amount <small>(MATIC)</small>
              </Label>
              <InputText type="number" />
            </InputRow>
            <InputRow>
              <Label>Max Contributors</Label>
              <InputText type="text" />
            </InputRow>
          </div>
        </ProjectContainer>

        <ProjectContainer>
          <div className="title-container">
            <div className="dot" />
            <div className="title">Project Detail</div>
          </div>
          <div className="content">
            <InputRow>
              <Label>Address</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>Name</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>Portfolio</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>Instagram</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>Facebook</Label>
              <InputText type="text" />
            </InputRow>
            <InputRow>
              <Label>Twitter</Label>
              <InputText type="text" />
            </InputRow>
            <CreateButton>Create</CreateButton>
          </div>
        </ProjectContainer>
      </Content>
      <Footer />
    </div>
  )
}

export default Create
